### ISSUE TITLE
Zero Zoom delay with Sniper Rifle

### ISSUE THREAD

**Issue by darkshade9** [actionquake/quake2-rerelease-dll#15]
Currently there is no zoom delay when zooming in with `weapon` or `lens`.  This may have something to do with frame timing changes.

Close when:
- Sniper rifle zoom delay is restored to normal

**Comment by mikota** [comment]
There is now a 500ms initial zoom delay and 200ms delay when switching between 2x 4x 6x zoom. I guesstimated the timings - will try to find exact in TNG source code or gameplay recording

**Comment by darkshade9** [comment]
I think originally there was a [600ms (6 frame) delay when going from no zoom to 2x zoom](https://github.com/actionquake/aq2-tng/blob/0d261c1212313d4a4a534e17bc75b43f07ddfc3d/source/a_cmds.c#L469) and no delay on 2x-4x-6x (other than the 100ms client delay)

**Comment by mikota** [comment]
Thanks, that makes sense. Looking at a gameplay recording, the delay between no zoom and 2x zoom seemed to be 700ms. I assume that's 600ms from the 6 `idle_frame`'s + the 100ms client delay, so I set the delays to be 700ms and 100ms respectively (could be changed to 675 and 75 if that makes more sense). Player can't shoot during the initial zoom-in but can during the other ones, as per original AQ2. The delays can be tweaked with `SNIPER_ZOOM_IN_TIME` and `SNIPER_ZOOM_NEXT_TIME`.
